name: example_hive
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  msh_checkbox: ^1.1.1
  time_pickerr: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.1
flutter:
  uses-material-design: true

  assets:
   - assets/fonts/ 
   - assets/images/

  fonts:
  - fonts:
    - asset: assets/fonts/ShabnamMedium.ttf
    family: ShabnamMedium
